version: '3.1'

services:

  postgres:
    image: postgres:10
    ports:
     - 5555:5432
    environment:
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test

  mysql:
    image: mysql:8
    ports:
     - 5556:3306
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=test
